# Generated by Django 3.0.6 on 2021-03-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
