# Generated by Django 3.0.6 on 2021-04-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210407_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_delivered_date',
            field=models.DateTimeField(null=True),
        ),
    ]
